### ISSUE TITLE
Unable to connect to MongoDB

### ISSUE THREAD

**Issue by AnthonySmith01** [rgroult/MobDistTool#6]
Hi

Thank you for this great tool. 👍 
Apologies if this is a stupid question, I'm a bit of a noob with using these tools.

I'm trying to run mdt from docker but get this error:

```
Observatory listening on http://0.0.0.0:8181
[2017-01-10 03:10:09.748249] INFO RPC: MDT starting ...
[2017-01-10 03:10:09.755826] INFO RPC: logging file : mdt_logs_20170110.txt
[2017-01-10 03:10:09.758326] INFO RPC: mongo initializing on  mongodb://localhost:27017/mdt_dev
Unhandled exception:
SocketException: OS Error: Connection refused, errno = 111, address = localhost, port = 36890
#0      _ConnectionManager._connect.<_connect_async_body> (package:mongo_dart/src/network/connection_manager.dart)
#1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
#2      _RootZone.runBinary (dart:async/zone.dart:1210)
#3      _FutureListener.handleError (dart:async/future_impl.dart:146)
#4      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:649)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:671)
#6      _Future._completeError (dart:async/future_impl.dart:485)
#7      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:537)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#10     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

Any ideas?

**Comment by rgroult** [comment]
Hello,
The docker container only contains MDT, you have to add and link to a mongoDB container through ENV values.
Maybe I should generate a full sample container image.. (with server and database)

**Comment by AnthonySmith01** [comment]
Ah right, yep that makes sense.

I'll go learn some more about docker. :)
